In [14]:
import numpy as np

#можно сгенерировать список в массив
list = [2, 3.5, 3]

array = np.array(list)
print (array)

#свойства массива
print (array.ndim) #мера 
print (array.shape) #размер 
print (array.dtype) #тип

[2.  3.5 3. ]


dtype('float64')

In [4]:
#список списков одинаковой длины можно преобразовать в многомерный массив:

list = [[3,4,5],[1,1,3]]
array = np.array(list)
print (array)

[[3 4 5]
 [1 1 3]]


In [17]:
#массив из нулей
np.zeros((2,3))

array([1., 1., 1.])

In [18]:
#массив из единиц
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [21]:
#можно привести тип массива к другому
arr = np.array([1,2,3])
print(arr.dtype)
arr = arr.astype(np.float64)
arr.dtype

int32


dtype('float64')

In [27]:
#операции над массивами
arr = np.random.randint(-1,5,size=(2,2))
print(arr)
print(arr+arr)
print(arr*arr)
print(arr+5)
print(arr/2)


[[4 1]
 [2 2]]
[[8 2]
 [4 4]]
[[16  1]
 [ 4  4]]
[[9 6]
 [7 7]]
[[2.  0.5]
 [1.  1. ]]


Важнейшее отличие от 
списков состоит в том, что срез массива является представлением исходного массива. Это означает, что данные на самом деле не копируются, а любые изменения, 
внесенные в представление, попадают и в исходный массив.
Чтобы получить копию, а не представление среза массива, нужно выполнить операцию копирования явно, например: arr[5:8].copy().


In [34]:
#булево индексирование
names = np.array(['kate','ivan','olga','ivan'])
mask = (names == 'ivan') | (names == 'kate')

In [37]:
numbers = np.random.rand(4,2)
numbers[mask]

array([[0.65335756, 0.47268134],
       [0.36892091, 0.97313328],
       [0.14693695, 0.83514164]])

 Ключевые слова Python and и or с булевыми массивами не работают.
 

In [40]:
numbers[numbers>0.5] = 0
numbers

array([[0.        , 0.47268134],
       [0.36892091, 0.        ],
       [0.10341679, 0.        ],
       [0.14693695, 0.        ]])

### Задача:
У вас есть массив температур за последнюю неделю в городе (в градусах Цельсия):

temperatures = np.array([25, 28, 31, 30, 22, 27, 29])

Ваша задача:

* Найдите все дни, когда температура была выше 27 градусов.
* Уменьшите температуру на 2 градуса в те дни, когда температура была выше 27 градусов.
* Найдите среднюю температуру за неделю после корректировки.

In [47]:
temperatures = np.array([25, 28, 31, 30, 22, 27, 29])

print (temperatures[temperatures>27])
temperatures[temperatures>27]-=2
print (temperatures)
print(f"{sum(temperatures)/len(temperatures):.2f}")
print(f"{np.mean(temperatures):.2f}")


[28 31 30 29]
[25 26 29 28 22 27 27]
26.29
26.29


### Задача:

Вы работаете с данными о продажах в онлайн-магазине за последний месяц. У вас есть массив данных, представляющий ежедневные продажи в долларовом эквиваленте:



sales = np.array([150, 200, 180, 220, 170, 190, 210, 250, 300, 270, 230, 250, 
                  240, 260, 280, 290, 310, 320, 330, 340, 300, 290, 270, 260, 
                  250, 240, 220, 210, 230, 250, 270, 290, 310, 330, 340, 350, 
                  360, 370, 380, 390, 400, 410, 420, 430, 440, 450])

__Ваша задача:__

* Найдите все дни, когда продажи были выше 300 долларов.
* Рассчитайте среднее значение продаж для этих дней.
* Найдите количество дней, когда продажи были выше 300 долларов, и процент от общего количества дней.
* Определите, сколько денег было заработано в дни с продажами выше 300 долларов, и сравните это с общим доходом за месяц.

In [55]:
sales = np.array([150, 200, 180, 220, 170, 190, 210, 250, 300, 270, 230, 250, 
                  240, 260, 280, 290, 310, 320, 330, 340, 300, 290, 270, 260, 
                  250, 240, 220, 210, 230, 250, 270, 290, 310, 330, 340, 350, 
                  360, 370, 380, 390, 400, 410, 420, 430, 440, 450])

days = np.arange(46)
days+=1
days
#Найдите все дни, когда продажи были выше 300 долларов.
print (days[sales>300])
#Рассчитайте среднее значение продаж для этих дней.
print(f"{np.mean(sales[sales>300]):.2f}")
#Найдите количество дней, когда продажи были выше 300 долларов, и процент от общего количества дней.
print(len(days[sales>300]))
print(f"{len(days[sales>300])/len(sales)*100:.2f}%")
#Определите, сколько денег было заработано в дни с продажами выше 300 долларов, и сравните это с общим доходом за месяц.
print(sum(sales[sales>300]))
print(f"{sum(sales[sales>300])/sum(sales)*100:.2f}%")

[17 18 19 20 33 34 35 36 37 38 39 40 41 42 43 44 45 46]
371.11
18
39.13%
6680
49.67%


In [61]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr[4,3]

4.0

У вас есть массив, содержащий данные о температуре воздуха (в градусах Цельсия) за каждый час в течение суток. Вам нужно отсортировать температуры по возрастанию и вывести отсортированный массив.

In [2]:
import numpy as np
temp = np.array(input().split(), dtype = float)
#Метод sort() сортирует массив на месте и не возвращает новый отсортированный массив.
temp.sort()
print(temp)

[-8. -4. -3. -1.  0.  1.  2.  3.  5.  6.  7.  8.  9. 10. 12. 14. 15. 18.
 19. 20. 23. 24. 29. 30.]


Случайные блуждания

In [25]:
nwalks = 500
nsteps = 100
steps = np.random.normal(loc=0, scale=1,size=(nwalks, nsteps))
#нарастающая сумма
draws = steps.cumsum(1)
#строчки, в которых достигается значение 10 и больше
hit10 = (np.abs(draws)>=10).any(1)
#первые индексы, в строчке, где достигается значение 10 и больше
ar = (np.abs(draws[hit10]>=10)).argmax(1)
#средний индекс
ar.mean()

23.717105263157894

В настольной игре Скрабл (Scrabble) каждая буква имеет определенную ценность. В случае с английским алфавитом очки распределяются так:

A, E, I, O, U, L, N, S, T, R – 1 очко;
D, G – 2 очка;
B, C, M, P – 3 очка;
F, H, V, W, Y – 4 очка;
K – 5 очков;
J, X – 8 очков;
Q, Z – 10 очков.
А русские буквы оцениваются так:

А, В, Е, И, Н, О, Р, С, Т – 1 очко;
Д, К, Л, М, П, У – 2 очка;
Б, Г, Ё, Ь, Я – 3 очка;
Й, Ы – 4 очка;
Ж, З, Х, Ц, Ч – 5 очков;
Ш, Э, Ю – 8 очков;
Ф, Щ, Ъ – 10 очков.
Напишите программу, которая вычисляет стоимость введенного пользователем слова. Будем считать, что на вход подается только одно слово, которое содержит либо только английские, либо только русские буквы.

In [27]:
dict = {
    1:'AEIOULNSTRАВЕИНОРСТ',
    2:'DGДКЛМПУ',
    3:'BCMPБГЁЬЯ',
    4:'KЙЫ',
    5:'JXЖЗХЦЧ',
    8:'JXШЭЮ',
    10:'QZФЩЪ'
}
text = input().upper()
print(sum([k for i in text for k,v in dict.items() if i in v]))

5


Турист собирается в поход. Он сможет нести N кг вещей. Но вещей, которые он запланировал уложить в рюкзак, оказалось намного больше. Нужно определить, какие вещи от наиболее тяжелых к самым легким поместятся в рюкзак.

Пример ввода:
10

Пример вывода:
палатка
спальный мешок
удочка
термос
салфетки
жвачка

In [ ]:
things = {'зажигалка': 20, 'компас': 100, 'фрукты': 500, 'рубашка': 300,
      	'термос': 1000, 'аптечка': 200, 'куртка': 600, 'бинокль': 400, 'удочка': 1200,
          'салфетки': 40, 'бутерброды': 820, 'палатка': 5500, 'спальный мешок': 2250, 'жвачка': 10}

N = int(input())

while N>0:
    k = max(things.values)
    N -=k/100
    print(things.keys where )
